### ISSUE TITLE
AssertionError: Line 89 in __init__.py

### ISSUE THREAD

**Issue by CSynodinos** [AlJohri/docx2pdf#46] opened 2021-10-23 12:54 UTC
Hi,

I have been using your library to do multiple file conversions, but I run into an AssetionError when I tried to convert a .doc file.

By reading your code, it's pretty clear that only .docx files are acceptable input arguments. Is it possible to add .doc support as well?

Edit: Saw that there is another issue thread made a year ago. Is .doc support still planned?

Thank you

**Comment by AlJohri** [comment] 2021-12-11 17:08
@CSynodinos I haven't had time to add support for `.doc` but would be happy to accept a PR to do so!

**Comment by AlJohri** [comment] 2021-12-11 17:08
Closing as duplicate of #4

**Closed by AlJohri** 2021-12-11 17:08 UTC
