### ISSUE TITLE
why not support linux ?

### ISSUE THREAD

**Issue by lqzerogg** [AlJohri/docx2pdf#95] opened 2023-11-06 10:20 UTC
most servers are linux. Is this because MS does not support api for linux?

**Comment by AlJohri** [comment] 2023-11-06 11:24
This program requires Microsoft Word to be installed, which as I understand it only runs on Windows and macOS. It uses the Microsoft Word APIs to do the conversion.

Also see this previous issue: https://github.com/AlJohri/docx2pdf/issues/22

Closing as dupe of #11

**Closed by AlJohri** 2023-11-06 11:24 UTC
